### ISSUE TITLE
crash when file is uploaded

### ISSUE THREAD

**Issue by sandsmark** [ltworf/localslackirc#104]
in PMs, and the stacktrace stuff seems broken as well.

```
Traceback (most recent call last):
File "irc.py", line 498, in <module>
main()
File "irc.py", line 492, in main
ircclient.slack_event(sl_event)
File "irc.py", line 378, in slack_event
self._message(f.announce())
File "/home/sandsmark/src/localslackirc/slack.py", line 160, in announce
channel=(self.channels + self.groups).pop(),
IndexError: pop from empty list
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "irc.py", line 502, in <module>
traceback.print_last()
File "/usr/lib/python3.6/traceback.py", line 169, in print_last
raise ValueError("no last exception")
ValueError: no last exception
```

**Comment by ltworf** [comment]
When you upload or someone else does?

**Comment by sandsmark** [comment]
someone else

**Comment by ltworf** [comment]
This thing was fixed in Nov https://github.com/ltworf/localslackirc/commit/c6c3a49fb706986808579e6916db0ebd738cee68

Closing this.
