### ISSUE TITLE
PM with image: index error: pop from empty list

### ISSUE THREAD

**Issue by daniel-Jones** [ltworf/localslackirc#111]
```
{'type': 'im_created', 'user': 'UAM222ENP', 'channel': {'id': 'DFPS20F5K', 'created': 1548452052, 'is_im': True, 'is_org_shared': False, 'user': 'UAM222ENP', 'last_read': '0000000000.000000', 'latest': None, 'unread_count': 0, 'unread_count_display': 0, 'is_open': False}, 'event_ts': '1548452052.011000'}
Message(channel='DFPS20F5K', user='UAM222ENP', text='message\n\nmultiple lines')
FileShared(file_id='FFR32HRUN', user_id='UAM222ENP', ts=1548452078.0008)
Traceback (most recent call last):
  File "./irc.py", line 426, in <module>
    main()
  File "./irc.py", line 419, in main
    ircclient.slack_event(sl_event)
  File "./irc.py", line 322, in slack_event
    self._message(f.announce())
  File "/home/daniel_j/programming/python/localslackirc/slack.py", line 159, in announce
    channel=(self.channels + self.groups).pop(),
IndexError: pop from empty list
```

Granted, I am on f1809fa from July 30th ... but haven't found this mentioned anywhere. Probably about time I update.

**Comment by ltworf** [comment]
Can you try with master?

That specific line is different in master.

**Comment by daniel-Jones** [comment]
Didn't occur on master, so I shall close this. Cheers.
