### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by userappgate** [ltworf/localslackirc#255]
```
Login in slack
Traceback (most recent call last):
  File "/usr/bin/localslackirc", line 873, in <module>
    main()
  File "/usr/bin/localslackirc", line 848, in main
    asyncio.run(irc_listener())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/bin/localslackirc", line 820, in irc_listener
    await sl_client.login()
  File "/usr/share/localslackirc/slack.py", line 359, in login
    self.login_info = await self.client.login(15)
  File "/usr/share/localslackirc/slackclient/client.py", line 97, in login
    raise SlackConnectionError("RTM connection attempt failed")
slackclient.exceptions.SlackConnectionError: message=None reply=None
```

**Comment by WillForan** [comment]
i hit this when `~/.localslackirc` did not end with `\n`  (created with `xclip -o > .localslackirc`)

```
 file .localslackirc 
.localslackirc: ASCII text, with no line terminators
```

editing the file resolved `RTM connection attempt failed`

**Comment by ltworf** [comment]
Boh, closing… that file got completely deleted.
