### ISSUE TITLE
Crash shortly after connecting and joining channels

### ISSUE THREAD

**Issue by zdykstra** [ltworf/localslackirc#287]
I built a new image from the Dockerfile out of a current git `master` checkout. I can connect to localslackirc via Hexchat and join all of my channels. On connection, the initial channel that Hexchat has selected shows this:

`:Incorrect is erroneous. Retrying with ...`

Roughly 20 seconds after connecting, the instance dies and I'm disconnected. 

The trace from the container is provided below.

```
Traceback (most recent call last):
  File "/localslackirc/irc.py", line 958, in <module>
    main()
  File "/localslackirc/irc.py", line 933, in main
    asyncio.run(irc_listener())
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/localslackirc/irc.py", line 913, in irc_listener
    await asyncio.gather(
  File "/localslackirc/irc.py", line 944, in from_irc
    await ircclient.command(cmd.strip())
  File "/localslackirc/irc.py", line 730, in command
    await handlers[cmdid](cmd)
  File "/localslackirc/irc.py", line 145, in _nickhandler
    _, nick = cmd.split(b' ', 1)
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by zdykstra** [comment]
```
cmd: b'NICK zdykstra'
cmd: b'NICK zdykstra-1'
cmd: b'NICK'
```

In HexChat, there are three fields for defining a Nick name (first, second, third choice). I had the first two filled out, and the third was left empty.  Filling out the third entry allows the split to have the required number of arguments from each `/nick` attempt by HexChat. Should be easy to guard against this condition in irc.py.
