### ISSUE TITLE
crashes when I'm invited to a new channel

### ISSUE THREAD

**Issue by terceiro** [ltworf/localslackirc#290]
These are the logs (running with debug enabled):

```
-- Journal begins at Tue 2020-11-17 13:41:32 -03, ends at Wed 2021-04-07 11:25:05 -03. --
abr 07 11:04:45 lemur localslackirc-linaro[626229]: {'type': 'channel_joined', 'channel': {'id': 'C010DLP3QUB', 'name': 'tuxbuild-bhoj-stdout', 'is_channel': True, 'is_group': False, 'is_im': False, 'created': 1585138306, 'is_archived': False, 'is_general': False, 'unlinked': 0, 'name_normalized': 'tuxbuild-bhoj-stdout', 'is_shared': False, 'is_frozen': False, 'parent_conversation': None, 'creator': 'UMFDUUUAU', 'is_ext_shared': False, 'is_org_shared': False, 'shared_team_ids': ['T03G6GWC6'], 'pending_shared': [], 'pending_connected_team_ids': [], 'is_pending_ext_shared': False, 'is_member': True, 'is_private': False, 'is_mpim': False, 'last_read': '1617804251.001500', 'latest': {'type': 'message', 'subtype': 'bot_message', 'text': 'SQS queue size: 496; ASG desired capacity: 382 -&gt; 496', 'ts': '1617804251.001500', 'username': 'tux-lambda', 'icons': {'emoji': ':penguin:', 'image_64': 'https://a.slack-edge.com/production-standard-emoji-assets/13.0/apple-large/1f427.png'}, 'bot_id': 'BM8T57ULR'}, 'unread_count': 0, 'unread_count_display': 0, 'topic': {'value': '', 'creator': '', 'last_set': 0}, 'purpose': {'value': '', 'creator': '', 'last_set': 0}, 'previous_names': [], 'priority': 0}}
abr 07 11:04:45 lemur localslackirc-linaro[626229]: {'type': 'channel_joined', 'channel': {'id': 'C010DLP3QUB', 'name': 'tuxbuild-bhoj-stdout', 'is_channel': True, 'is_group': False, 'is_im': False, 'created': 1585138306, 'is_archived': False, 'is_general': False, 'unlinked': 0, 'name_normalized': 'tuxbuild-bhoj-stdout', 'is_shared': False, 'is_frozen': False, 'parent_conversation': None, 'creator': 'UMFDUUUAU', 'is_ext_shared': False, 'is_org_shared': False, 'shared_team_ids': ['T03G6GWC6'], 'pending_shared': [], 'pending_connected_team_ids': [], 'is_pending_ext_shared': False, 'is_member': True, 'is_private': False, 'is_mpim': False, 'last_read': '1617804251.001500', 'latest': {'type': 'message', 'subtype': 'bot_message', 'text': 'SQS queue size: 496; ASG desired capacity: 382 -&gt; 496', 'ts': '1617804251.001500', 'username': 'tux-lambda', 'icons': {'emoji': ':penguin:', 'image_64': 'https://a.slack-edge.com/production-standard-emoji-assets/13.0/apple-large/1f427.png'}, 'bot_id': 'BM8T57ULR'}, 'unread_count': 0, 'unread_count_display': 0, 'topic': {'value': '', 'creator': '', 'last_set': 0}, 'purpose': {'value': '', 'creator': '', 'last_set': 0}, 'previous_names': [], 'priority': 0}}
abr 07 11:04:46 lemur localslackirc-linaro[626229]: {'type': 'member_joined_channel', 'user': 'U01082R9W9H', 'channel': 'C010DLP3QUB', 'channel_type': 'C', 'team': 'T03G6GWC6', 'inviter': 'UMFDUUUAU', 'event_ts': '1617804285.001800', 'ts': '1617804285.001800'}
abr 07 11:04:46 lemur localslackirc-linaro[626229]: Closing connections
abr 07 11:04:46 lemur localslackirc-linaro[626229]: Writing status to /var/tmp/localslackirc-status-linaro
abr 07 11:04:46 lemur localslackirc-linaro[626229]: Cancelling running tasks
abr 07 11:04:56 lemur localslackirc-linaro[626229]: Traceback (most recent call last):
abr 07 11:04:56 lemur localslackirc-linaro[626229]:   File "/home/terceiro/src/localslackirc/irc.py", line 971, in <module>
abr 07 11:04:56 lemur localslackirc-linaro[626229]:     main()
abr 07 11:04:56 lemur localslackirc-linaro[626229]:   File "/home/terceiro/src/localslackirc/irc.py", line 946, in main
abr 07 11:04:56 lemur localslackirc-linaro[626229]:     asyncio.run(irc_listener())
abr 07 11:04:56 lemur localslackirc-linaro[626229]:   File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
abr 07 11:04:56 lemur localslackirc-linaro[626229]:     return loop.run_until_complete(main)
abr 07 11:04:56 lemur localslackirc-linaro[626229]:   File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
abr 07 11:04:56 lemur localslackirc-linaro[626229]:     return future.result()
abr 07 11:04:56 lemur localslackirc-linaro[626229]:   File "/home/terceiro/src/localslackirc/irc.py", line 926, in irc_listener
abr 07 11:04:56 lemur localslackirc-linaro[626229]:     await asyncio.gather(
abr 07 11:04:56 lemur localslackirc-linaro[626229]:   File "/home/terceiro/src/localslackirc/irc.py", line 961, in to_irc
abr 07 11:04:56 lemur localslackirc-linaro[626229]:     ev = await sl_client.event()
abr 07 11:04:56 lemur localslackirc-linaro[626229]:   File "/home/terceiro/src/localslackirc/slack.py", line 851, in event
abr 07 11:04:56 lemur localslackirc-linaro[626229]:     self._get_members_cache[ev.channel].add(ev.user)
abr 07 11:04:56 lemur localslackirc-linaro[626229]: KeyError: 'C010DLP3QUB'
abr 07 11:04:56 lemur systemd[2798]: localslackirc@linaro.service: Main process exited, code=exited, status=1/FAILURE
abr 07 11:04:56 lemur systemd[2798]: localslackirc@linaro.service: Failed with result 'exit-code'.
abr 07 11:04:56 lemur systemd[2798]: localslackirc@linaro.service: Consumed 8.464s CPU time.
abr 07 11:04:56 lemur systemd[2798]: localslackirc@linaro.service: Scheduled restart job, restart counter is at 2.
abr 07 11:04:56 lemur systemd[2798]: Stopped Localslackirc.
abr 07 11:04:56 lemur systemd[2798]: localslackirc@linaro.service: Consumed 8.464s CPU time.
abr 07 11:04:56 lemur systemd[2798]: Started Localslackirc.
abr 07 11:04:56 lemur localslackirc-linaro[1000696]: Status file at: /var/tmp/localslackirc-status-linaro
```

**Comment by ltworf** [comment]
I made a PR but it only fixes the crash, not the fact that the channel is unknown to it.

For that, I'm not sure what is needed. I guess some event about the channel creation got received at some point.

**Comment by terceiro** [comment]
aren't the 3 messages right before the crash in the log above exactly that?

**Comment by ltworf** [comment]
I guess so, i had presumed the channel was newly created, but makes sense that it wasn't cached if it wasn't joined before.
