### ISSUE TITLE
crashes if I send a /whois commands with no arguments

### ISSUE THREAD

**Issue by terceiro** [ltworf/localslackirc#291]
The log:

```
Closing connections
Writing status to /var/tmp/localslackirc-status-linaro
Cancelling running tasks
Traceback (most recent call last):
  File "/home/terceiro/src/localslackirc/irc.py", line 971, in <module>
    main()
  File "/home/terceiro/src/localslackirc/irc.py", line 946, in main
    asyncio.run(irc_listener())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/terceiro/src/localslackirc/irc.py", line 926, in irc_listener
    await asyncio.gather(
  File "/home/terceiro/src/localslackirc/irc.py", line 957, in from_irc
    await ircclient.command(cmd.strip())
  File "/home/terceiro/src/localslackirc/irc.py", line 743, in command
    await handlers[cmdid](cmd)
  File "/home/terceiro/src/localslackirc/irc.py", line 371, in _whoishandler
    username = users.pop()
IndexError: pop from empty list
Exception ignored in: <function SlackClient.__del__ at 0x7f02aee95040>
Traceback (most recent call last):
  File "/home/terceiro/src/localslackirc/slackclient/client.py", line 68, in __del__
  File "/usr/lib/python3.9/asyncio/tasks.py", line 360, in create_task
RuntimeError: no running event loop
sys:1: RuntimeWarning: coroutine 'WebSocketCommonProtocol.close' was never awaited
```

**Comment by ltworf** [comment]
Well why did you send a whois with no arguments? :D

What is it supposed to do in actuality?

**Comment by terceiro** [comment]
low priority I would say though, I just reported because I had it happen to me
