### ISSUE TITLE
Exception in sl_client.event()

### ISSUE THREAD

**Issue by jikos** [ltworf/localslackirc#318]
From time to time, I get the crash below

Traceback (most recent call last):
  File "/localslackirc/localslackirc", line 24, in <module>
    main()
  File "/localslackirc/irc.py", line 955, in main
    asyncio.run(irc_listener())
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/localslackirc/irc.py", line 935, in irc_listener
    await asyncio.gather(
  File "/localslackirc/irc.py", line 970, in to_irc
    ev = await sl_client.event()
  File "/localslackirc/slack.py", line 857, in event
    self._get_members_cache[ev.channel].remove(ev.user)
KeyError: 'U02DDHA37DX'

and have to restart it. IRC client is hexchat, and it appears both when hexchat is directly connected to localsockirc, as well as when there is a ZNC bouncer in the middle.

**Comment by ltworf** [comment]
Hello, could you send me 15 or 20 lines before the error as well?

**Comment by jikos** [comment]
There unfortunately doesn't seem to be any output whatsoever even if I have DEBUG=1 set in my environment; I haven't got to debugging that yet. I am running it in docker container as follows:

**Comment by ltworf** [comment]
Are you sure the output isn't being sent to syslog?

**Comment by jikos** [comment]
As far as I can say, the docker image doesn't even include syslogd.

**Comment by ltworf** [comment]
I think they often mount /dev/log from the host?
