### ISSUE TITLE
crash when referring to ignored/not cached channels

### ISSUE THREAD

**Issue by ltworf** [ltworf/localslackirc#411]
```
lug 18 16:13:31 galatea localslackirc[100012]: Message(channel='QQQQ', user='QQQQQ', text='See <#ASDASDASD|>', thread_ts=None, files=[])
lug 18 16:13:32 galatea localslackirc[100012]: Closing connections
lug 18 16:13:32 galatea localslackirc[100012]: Writing status to /var/tmp/localslackirc-status
lug 18 16:13:32 galatea localslackirc[100012]: Cancelling running tasks
lug 18 16:13:32 galatea localslackirc[100012]: Traceback (most recent call last):
lug 18 16:13:32 galatea localslackirc[100012]:   File "/usr/bin/localslackirc", line 24, in <module>
lug 18 16:13:32 galatea localslackirc[100012]:     main()
lug 18 16:13:32 galatea localslackirc[100012]:   File "/usr/share/localslackirc/irc.py", line 1013, in main
lug 18 16:13:32 galatea localslackirc[100012]:     asyncio.run(restart_listener_loop())
lug 18 16:13:32 galatea localslackirc[100012]:   File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
lug 18 16:13:32 galatea localslackirc[100012]:     return runner.run(main)
lug 18 16:13:32 galatea localslackirc[100012]:            ^^^^^^^^^^^^^^^^
lug 18 16:13:32 galatea localslackirc[100012]:   File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
lug 18 16:13:32 galatea localslackirc[100012]:     return self._loop.run_until_complete(task)
lug 18 16:13:32 galatea localslackirc[100012]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lug 18 16:13:32 galatea localslackirc[100012]:   File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
lug 18 16:13:32 galatea localslackirc[100012]:     return future.result()
lug 18 16:13:32 galatea localslackirc[100012]:            ^^^^^^^^^^^^^^^
lug 18 16:13:32 galatea localslackirc[100012]:   File "/usr/share/localslackirc/irc.py", line 1009, in restart_listener_loop
lug 18 16:13:32 galatea localslackirc[100012]:     await irc_listener()
lug 18 16:13:32 galatea localslackirc[100012]:   File "/usr/share/localslackirc/irc.py", line 985, in irc_listener
lug 18 16:13:32 galatea localslackirc[100012]:     await asyncio.gather(
lug 18 16:13:32 galatea localslackirc[100012]:   File "/usr/share/localslackirc/irc.py", line 1030, in to_irc
lug 18 16:13:32 galatea localslackirc[100012]:     await ircclient.slack_event(ev)
lug 18 16:13:32 galatea localslackirc[100012]:   File "/usr/share/localslackirc/irc.py", line 739, in slack_event
lug 18 16:13:32 galatea localslackirc[100012]:     await self._message(sl_ev)
lug 18 16:13:32 galatea localslackirc[100012]:   File "/usr/share/localslackirc/irc.py", line 694, in _message
lug 18 16:13:32 galatea localslackirc[100012]:     lines = (await self.parse_message(prefix + text, source, yelldest)).encode('utf-8')
lug 18 16:13:32 galatea localslackirc[100012]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lug 18 16:13:32 galatea localslackirc[100012]:   File "/usr/share/localslackirc/irc.py", line 610, in parse_message
lug 18 16:13:32 galatea localslackirc[100012]:     r += '#' + (await self.sl_client.get_channel(t.val)).name_normalized
lug 18 16:13:32 galatea localslackirc[100012]:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lug 18 16:13:32 galatea localslackirc[100012]:   File "/usr/share/localslackirc/slack.py", line 637, in get_channel
lug 18 16:13:32 galatea localslackirc[100012]:     raise KeyError()
lug 18 16:13:32 galatea localslackirc[100012]: KeyError
```

**Comment by ltworf** [comment]
Fixed
