### ISSUE TITLE
Handle messages that don't have a user field

### ISSUE THREAD

**Issue by jimporter** [ltworf/localslackirc#48]
Apparently, some messages don't have a user field, causing a crash in the daemon. In particular, I see this with the waffle.io bot. Here's the error I get (message contents anonymized):

---

 ValueError: Value {'text': '', 'bot_id': 'BA6TC9J66', 'attachments': [{'fallback': 'so-and-so moved <https://github.com/org/repo/pull/123|#123> from In Progress to Done', 'pretext': '*so-and-so* moved <https://github.com/org/repo/pull/123|org/repo#123> from *In Progress* to *Done*', 'title': '#123 Issue Description', 'footer': '<https://waffle.io/org/repo/cards/guid|Open in Waffle>', 'id': 1, 'title_link': 'https://github.com/org/repo/pull/123', 'color': '78bdf2', 'fields': [{'title': 'Assignees', 'value': 'so-and-so', 'short': True}, {'title': 'Column', 'value': 'Done', 'short': True}], 'mrkdwn_in': ['pretext', 'text']}], 'type': 'message', 'subtype': 'bot_message', 'ts': '1526665855.000086'} could not be loaded into typing.Union[slack.LatestMessage, NoneType]

... does not contain fields: {'user'} which are necessary for type <class 'slack.LatestMessage'>

---

I don't personally care if I miss these messages, but it's not great if the daemon crashes. :( I'm happy to write a patch for this, but I wanted to file an issue first to get a chance to discuss the best implementation strategy.

(Apologies for the gross formatting in the log!)

**Comment by ltworf** [comment]
Are you using the latest version? It should no longer crash now when a message can't be handled.

If you can still do it with the latest version on master, can you send the full stacktrace?

**Comment by jimporter** [comment]
Her's the full traceback:

```
Traceback (most recent call last):
  File "irc.py", line 368, in <module>
    main()
  File "irc.py", line 357, in main
    ircclient.command(i)
  File "irc.py", line 291, in command
    handlers[cmdid](cmd)
  File "irc.py", line 72, in _userhandler
    for sl_chan in self.sl_client.channels():
  File "/home/jim/src/localslackirc/slack.py", line 249, in channels
    group for group in load(r['groups'], List[Channel])
  File "/home/jim/.virtualenvs/slack/lib/python3.6/site-packages/typedload/__init__.py", line 78, in load
    return loader.load(value, type_)
  File "/home/jim/.virtualenvs/slack/lib/python3.6/site-packages/typedload/dataloader.py", line 162, in load
    return func(self, value, type_)
  File "/home/jim/.virtualenvs/slack/lib/python3.6/site-packages/typedload/dataloader.py", line 188, in _listload
    return [l.load(v, t) for v in value]
  File "/home/jim/.virtualenvs/slack/lib/python3.6/site-packages/typedload/dataloader.py", line 188, in <listcomp>
    return [l.load(v, t) for v in value]
  File "/home/jim/.virtualenvs/slack/lib/python3.6/site-packages/typedload/dataloader.py", line 162, in load
    return func(self, value, type_)
  File "/home/jim/.virtualenvs/slack/lib/python3.6/site-packages/typedload/dataloader.py", line 248, in _namedtupleload
    params[k] = l.load(v, type_hints[k])
  File "/home/jim/.virtualenvs/slack/lib/python3.6/site-packages/typedload/dataloader.py", line 162, in load
    return func(self, value, type_)
  File "/home/jim/.virtualenvs/slack/lib/python3.6/site-packages/typedload/dataloader.py", line 285, in _unionload
    '\n'.join(exceptions)
```

It tries to load into `slack.LatestMessage`, which looks like it might be for historical messages? It's the first that happens after my client sends a CAP message to the server. If I fix this bit, I then see similar errors later when trying to make a `slack.MessageBot` object, but those don't crash the daemon.
