### ISSUE TITLE
Crash - occured while connected, no interactions

### ISSUE THREAD

**Issue by Hack5190** [ltworf/localslackirc#52]
Unknown command:  b'CAP LS'
WHO not supported on  b'hack5190'
{'type': 'file_public', 'file_id': 'FAUP2TZ98', 'user_id': 'U06H0E738', 'file': {'id': 'FAUP2TZ98'}, 'event_ts': '1527079501.000025'}
{'type': 'file_shared', 'file_id': 'FAUP2TZ98', 'user_id': 'U06H0E738', 'file': {'id': 'FAUP2TZ98'}, 'event_ts': '1527079501.000038'}
{'type': 'file_public', 'file_id': 'FAVKYPABY', 'user_id': 'U060CFZV2', 'file': {'id': 'FAVKYPABY'}, 'event_ts': '1527079617.000004'}
{'type': 'file_shared', 'file_id': 'FAVKYPABY', 'user_id': 'U060CFZV2', 'file': {'id': 'FAVKYPABY'}, 'event_ts': '1527079617.000029'}
Traceback (most recent call last):
  File "./irc.py", line 413, in <module>
    main()
  File "./irc.py", line 402, in main
    ircclient.command(i)
  File "./irc.py", line 334, in command
    handlers[cmdid](cmd)
  File "./irc.py", line 175, in _whohandler
    user = self.sl_client.get_user(i)
  File "/home/bouncer/SlackBridge/MAC-Bridge/slack.py", line 324, in get_user
    r = self.client.api_call("users.info", user=id_)
  File "/home/bouncer/SlackBridge/MAC-Bridge/slackclient/client.py", line 95, in api_call
    response_body = self.server.api_call(method, timeout=timeout, **kwargs)
  File "/home/bouncer/SlackBridge/MAC-Bridge/slackclient/server.py", line 225, in api_call
    response_json = json.loads(response.text)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by ltworf** [comment]
Oh they also send invalid json data now?

**Comment by ltworf** [comment]
Is this still happening?
