### ISSUE TITLE
Crash (#2) while idle

### ISSUE THREAD

**Issue by Hack5190** [ltworf/localslackirc#53]
Message(channel='C19MR7EM9', user='U0551BR0S', text='<@U85EWQA6P> new material. potentially relevant, depending.')
{'type': 'member_left_channel', 'user': 'U0551BR0S', 'channel': 'C19MR7EM9', 'channel_type': 'C', 'team': 'T04QVKUQG', 'event_ts': '1527081026.000176', 'ts': '1527081026.000176'}
{'user': 'U0551BR0S', 'user_profile': {'avatar_hash': 'a2c4932b8260', 'image_72': 'https://avatars.slack-edge.com/2015-06-02/5171603100_a2c4932b826006664a0b_72.jpg', 'first_name': 'Owen', 'real_name': 'Owen Pragel', 'display_name': 'owen.pragel', 'team': 'T04QVKUQG', 'name': 'owen.pragel', 'is_restricted': False, 'is_ultra_restricted': False}, 'type': 'message', 'subtype': 'channel_leave', 'team': 'T04QVKUQG', 'text': '<@U0551BR0S> has left the channel', 'channel': 'C19MR7EM9', 'event_ts': '1527081026.000191', 'ts': '1527081026.000191'}
{'type': 'file_public', 'file_id': 'FAU394EFJ', 'user_id': 'U04RHB76M', 'file': {'id': 'FAU394EFJ'}, 'event_ts': '1527081370.000280'}
Traceback (most recent call last):
  File "/home/bouncer/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/bouncer/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/home/bouncer/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/home/bouncer/.local/lib/python3.6/site-packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/home/bouncer/.local/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bouncer/.local/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/bouncer/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/bouncer/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/bouncer/.local/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/bouncer/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/bouncer/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/home/bouncer/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/home/bouncer/.local/lib/python3.6/site-packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/home/bouncer/.local/lib/python3.6/site-packages/urllib3/util/ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./irc.py", line 413, in <module>
    main()
  File "./irc.py", line 402, in main
    ircclient.command(i)
  File "./irc.py", line 334, in command
    handlers[cmdid](cmd)
  File "./irc.py", line 175, in _whohandler
    user = self.sl_client.get_user(i)
  File "/home/bouncer/SlackBridge/MAC-Bridge/slack.py", line 324, in get_user
    r = self.client.api_call("users.info", user=id_)
  File "/home/bouncer/SlackBridge/MAC-Bridge/slackclient/client.py", line 95, in api_call
    response_body = self.server.api_call(method, timeout=timeout, **kwargs)
  File "/home/bouncer/SlackBridge/MAC-Bridge/slackclient/server.py", line 224, in api_call
    response = self.api_requester.do(self.token, method, kwargs, timeout)
  File "/home/bouncer/SlackBridge/MAC-Bridge/slackclient/slackrequest.py", line 88, in do
    proxies=self.proxies
  File "/home/bouncer/.local/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/bouncer/.local/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/bouncer/.local/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/bouncer/.local/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/bouncer/.local/lib/python3.6/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

**Comment by ltworf** [comment]
You had no connection, I think I can make it handle those cases by restarting, but it needs to disconnect the IRC, so the user knows that something is up.

**Comment by Hack5190** [comment]
Odd that there wasn't a connection.  This same host was running a second instance of LSI (in a separate directory - connected to a different slack team) at the same time and it had no issues.

**Comment by ltworf** [comment]
What can I say… those are network errors
