### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED Mac OX

### ISSUE THREAD

**Issue by xypd** [ltworf/localslackirc#62]
I'm not sure how best to fix this problem. If anyone has any insight, it would be most appreciated.

Where is this pulling the cert from? local or from the slack server?

Thanks

Python: 3.7.0
Mac OSX: 10.13.3

```
$ python3 irc.py
{'ok': True, 'url': 'wss://cerberus-xxxx.lb.slack-msgs.com/websocket/long_token_here’, 'team': {'id': 'ZZZ789012', 'name': 'Some Team', 'domain': 'someteam'}, 'self': {'id': 'XXX123456', 'name': 'your name'}}
Failed RTM connect
Traceback (most recent call last):
  File "/Users/username/localslackirc/slackclient/server.py", line 156, in connect_slack_websocket
    http_proxy_auth=proxy_auth)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/websocket/_core.py", line 494, in create_connection
    websock.connect(url, **options)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/websocket/_core.py", line 217, in connect
    options.pop('socket', None))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/websocket/_http.py", line 126, in connect
    sock = _ssl_socket(sock, options.sslopt, hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/websocket/_http.py", line 253, in _ssl_socket
    sock = _wrap_sni_socket(sock, sslopt, hostname, check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/websocket/_http.py", line 232, in _wrap_sni_socket
    server_hostname=hostname,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 850, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 1108, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/username/localslackirc/slackclient/client.py", line 67, in rtm_connect
    self.server.rtm_connect()
  File "/Users/username/localslackirc/slackclient/server.py", line 131, in rtm_connect
    self.connect_slack_websocket(self.ws_url)
  File "/Users/username/localslackirc/slackclient/server.py", line 163, in connect_slack_websocket
    raise SlackConnectionError(message=str(e))
slackclient.exceptions.SlackConnectionError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1045)
Traceback (most recent call last):
  File "irc.py", line 402, in <module>
    main()
  File "irc.py", line 381, in main
    sl_event = next(sl_events)
StopIteration
```

**Comment by ltworf** [comment]
Problem is that I don't have an osx machine.

I suppose on linux there is some default root certificate that is missing on osx, but is used by the browser and you could resolve by importing that manually, from the browser to the system-wide… if that's what's going on there…
You can find out more info on the SSL certificate used by slack from the browser.

**Comment by ltworf** [comment]
Except it's illegal, since apple wants to force developers to buy their hardware or not develop for apple…

**Comment by xypd** [comment]
That true I suppose. And I wasn't suggesting that you do that. Was more thinking of a short term solution. Hopefully I can find a solution once I find more time.

**Comment by xypd** [comment]
Made some progress. Following this post [Python CA certificates for Mac](https://stackoverflow.com/questions/40684543/how-to-make-python-use-ca-certificates-from-mac-os-truststore) , I think I've gotten closer since I don't show the ssl error anymore.

However now I have an error 54, connection reset by peer.

```
python3 irc.py
{'ok': True, 'url': 'wss://cerberus-xxxx.lb.slack-msgs.com/websocket/long_token_here’, 'team': {'id': 'ZZZ789012', 'name': 'Some Team', 'domain': 'someteam'}, 'self': {'id': 'XXX123456', 'name': 'your name'}}
Unknown command:  b'\x16\x03\x01\x00\xa4\x01\x00\x00\xa0\x03\x03[A0+\xc0}\x0e|3\xe3\x1f\x88\xe5<\xf3\xcdG\xacm\x9e\xd1\x8ed\xb0OQ\t\xe9\xc8\xa2\xabR\x00\x00,\x00\xff\xc0,\xc0+\xc0$\xc0#\xc0'
Unknown command:  b"\xc0\t\xc0\x08\xc00\xc0/\xc0(\xc0'\xc0\x14\xc0\x13\xc0\x12\x00\x9d\x00\x9c\x00=\x00<\x005\x00/\x00"
Unknown command:  b'\x01\x00\x00K\x00\x00\x00\x0e\x00\x0c\x00\x00\t127.0.0.1\x00'
Traceback (most recent call last):
  File "irc.py", line 402, in <module>
    main()
  File "irc.py", line 384, in main
    text = s.recv(1024)
ConnectionResetError: [Errno 54] Connection reset by peer
```


```
lines:
      # Main loop
        timeout = 0.1
        while True:
            s_event = poller.poll(timeout)  # type: List[Tuple[int,int]]
            sl_event = next(sl_events)

            if s_event:
384             text = s.recv(1024)
                if len(text) == 0:
                    break
                #FIXME handle the case when there is more to be read
                for i in text.split(b'\n')[:-1]:
                    i = i.strip()
                    if i:
                        ircclient.command(i)

            if sl_event:
                print(sl_event)
                ircclient.slack_event(sl_event)
                timeout = 0.1
            else:
                timeout = 7

if __name__ == '__main__':
    try:
402        main()
           except KeyboardInterrupt:
              pass
```

**Comment by xypd** [comment]
So turnout after my last post that the final answer was to tick of the ssl switch in my client. This was also double checked with a few other clients.

So now it is working as expected with ONE slack profile at a time. Now to figure out multi-profile at once.

**Comment by daniel-Jones** [comment]
This isn't relevant to the ticket, however to use multiple slack workspaces (i think they're called?) you'll have to run mutiple instances of lsirc on different ports (-p PORT, see -h for options)

**Comment by xypd** [comment]
Hmm, interesting. Thanks Daniel most appreciated. I opened a [ticket #105](https://github.com/ltworf/localslackirc/issues/105#issue-367050547)  for this question, before I saw your suggestion. But happy you've given me something to work with.
